name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - scikit-image
  - seaborn
  - Pillow
  - sphinx-gallery
  - scikit-learn
  - dill
  - pandas
  - partd
  - bokeh
  - dask
